-- Usamos el rol de administrador para asegurar permisos de creación
USE ROLE ROLE_OT_ANALYTICS; 
USE WAREHOUSE WH_GOBERNANCE_XS;
USE DATABASE OT_CURATED;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE DAILY_TOWER_PERFORMANCE AS
SELECT 
    DATE(FECHA_REGISTRO) AS DIA,
    FAMILIA_PRODUCTO,
    AVG(TEMPERATURA_ENTRADA) AS TEMP_PROMEDIO_ENTRADA,
    AVG(TEMPERATURA_SALIDA) AS TEMP_PROMEDIO_SALIDA,
    SUM(FLUJO_DE_ENTRADA) AS TOTAL_FLUJO_M3,
    -- Calculamos la eficiencia térmica simple
    AVG(TEMPERATURA_ENTRADA - TEMPERATURA_SALIDA) AS DELTA_TERMICO_PROM
FROM OT_CLEAN.TRANSFORMED.TORRE_SQL_CLEAN
GROUP BY 1, 2
ORDER BY 1 DESC;